### ISSUE TITLE
PKGBUILD does not work on latest version of Arch

### ISSUE THREAD

**Issue by ddevault** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#1]
It complains about not having the kernel headers installed and not having a config file.

**Comment by ddevault** [comment]
Further research: everything has made it into 4.4-rc8, so I'm installing that and then I'll grab the firmware from here with the 4.4 method. PKGBUILD is still borken, though, so I'll leave this issue open for now.

**Comment by ajaybhatia** [comment]
You should only run install_for_kernel_4.4_rc2.sh and you're ready to use your wifi adapter. I've mentioned this in README. Hope this will work.

**Comment by ajaybhatia** [comment]
Below 4.4 you need linux-header package to be installed before executing makepkg. That's the dependency you need.
