### ISSUE TITLE
Bad md5sum for qca9377.tar.xz

### ISSUE THREAD

**Issue by chc4** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#2]
I get `756934dba6b59e2ee19922b63b8a97bb  qca9377.tar.xz` from md5sum, but the PKGBUILD expects `cb8023f987bdc485c3b4bf1be31b8ceb`

I cloned the repo twice and got the same thing both times. Did a commit forget to update the md5sum, or is GitHub trying to mitm a kernel driver :(

**Comment by ajaybhatia** [comment]
Oh sorry! I forget to update checksum in PKGBUILD. I updated it and push my changes.
