### ISSUE TITLE
Poor performance on QCA9377

### ISSUE THREAD

**Issue by theov3rc0mer** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#3]
The driver works great, however I can get a maximum speed of 1-1,5 Mb/s and this speed is actually shown under "maximum speed" in the connections info.
![schermata del 2016-06-24 17-59-14](https://cloud.githubusercontent.com/assets/19979868/16343308/9c8b7c1c-3a36-11e6-9ffb-0f57470197f8.png)

**Comment by ajaybhatia** [comment]
Sorry theov3rc0mer, I don't have this device anymore therefore I can't help you.  Moreover Atheros is not good device and it seldom has many hardware issues like very low range and power dissipation.
