### ISSUE TITLE
Corrupts disk!

### ISSUE THREAD

**Issue by henriktorget** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#5]
I ran the install.sh on Linux Mint Serena 18.1 but it corrupted the whole drive.
Earlier i tested by running it from my usb-drive and it corrupted that as well. 
After running it in terminal mode it shows some red warnings before bricking the system.

**Comment by ajaybhatia** [comment]
@henriktorget A script can't corrupt your drive. You may be having some another problem. Number of users are using this repo on their daily basis for using WiFi and no one complaint this issue.
