### ISSUE TITLE
Wifi works - but causes Bluetooth problems

### ISSUE THREAD

**Issue by hetzbh** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#6]
The QCA9377 is a combo chip - it provides support for Wifi as well as Bluetooth 4.1

However, using these drivers (or the merged ones - I'm using Fedora 25) with Bluetooth - causing the Wifi to loose signal, slow connection until it drops. This happens every time the when you try to stream a movie from remote to a Bluetooth speakers, for example.

**Comment by ajaybhatia** [comment]
Dear @hetzbh I no longer have this hardware. I'm sorry I can't help you.
