### ISSUE TITLE
On Dual Boot, after installing I can't access GRUB

### ISSUE THREAD

**Issue by ralexrdz** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#7]
I had Windows and Linux Mint installed, always going to GRUB where I could select to boot Linux Mint.

When installing driver, I can't access GRUB anymore and can not load into Linux Mint.
Don't even know if driver worked.

**Comment by GetRektBoy724** [comment]
why @ajaybhatia close this issue...
@ajaybhatia dont even replying...
lmao i dont care tho :)
NO OFFENSE
