### ISSUE TITLE
WHAT THE FUCK

### ISSUE THREAD

**Issue by ghost** [ajaybhatia/Qualcomm-Atheros-QCA9377-Wifi-Linux#8]
WHY THE FUCK DOES THE INSTALL SCRIPT REBOOT?
THIS IS NOT A SHITTY WINDOWS DRIVER, WE DON'T REBOOT COMPUTERS WHEN WE INSTALL LINUX DRIVERS.

**Comment by Admia1** [comment]
YES WE DO !!!
you need to reboot or sign out and sign in after installing usually.

**Comment by ghost** [comment]
And name me one Linux user who doesn't know that he needs to reboot/modprobe/up the interface or whatever else is necessary, you don't go around rebooting people's computers. I had like 10 days worth of unsaved work open on that workstation.

**Comment by flatline-studios** [comment]
Name me one Linux user who doesn't save their work in 10 days!! 

Not to mention, one that runs a shell script found on the net without reading it first! 

Jeez.

**Comment by ackspony** [comment]
Despite the irrelevant response from @flatline-studios , and the unnecessary cursing in the title, the OP is 100% correct. This is not expected behavior. Even windows installers give a warning prompt/option.

**Comment by GetRektBoy724** [comment]
lmao this issue was fucking funny :)
